### ISSUE TITLE
Maybe I misunderstand VpnCloud's (-s subnet) purpose

### ISSUE THREAD

**Issue by bmullan** [dswd/vpncloud#48]
The documentation for the config option for "subnet" says...

> -s <subnet>, --subnet <subnet>:
> 
> The local subnets to use. This parameter should be in the form address/prefixlen where address is an IPv4 address, an IPv6 address, or a MAC address. The prefix length is the number of significant front bits that distinguish the subnet from other subnets. Example: 10.1.1.0/24.

So if I have 2 **_remote_** servers running VpnCloud  Node1  and Node 2

And on Node 2 I have a 10.1.1.0/24 subnet.

If I configure VpnCloud on Node 2 with

>  **-s 10.1.1.0/24**

If on Node 2 I have 2 VMs (10.1.1.30) and 10.1.1.140)

From Node 1 am I supposed to be able to PING those 2 VM's because of the (-s 10.1.1.0/24) in Node 2's configuration?

If the answer is yes then its not working for me?

**Comment by dswd** [comment]
The subnet config in VpnCloud only configures the routing INSIDE VpnCloud (i.e. that one VpnCloud node sends packets directly to another node). This setting is also only used in routing mode (or normal mode on TUN interfaces).
This setting however will not affect the routing OUTSIDE Vpncloud (i.e. in the linux kernel). So you still have to set a route for that subnet via the VpnCloud interface for this to work. (You have to do that on both sides in order to ping.)
I might clarify that in the documentation.

**Comment by bmullan** [comment]
Thaks
